
<?php
$this->headScript()
    ->appendFile($this->basePath('js/Payroll/excel-upload/helper.js'));
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/js-xlsx-master/dist/xlsx.full.min.js'))
        ->appendFile($this->basePath('js/Payroll/employee-grade/excel.js'));
?>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.updateGradesLink = '<?php echo $this->url("employeeGrade", ["action" => "updateGradeDetails"]); ?>';
    document.acl =<?php echo json_encode($acl); ?>;
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\flatValue')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div>
    <div class="row">
        <div class="col-sm-12 ">
            <div class="portlet light bg-inverse">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-paper-plane font-green-haze"></i>
                        <span class="caption-subject bold font-green-haze uppercase"> Import From Excel</span>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-sm-4">
                            <label>Browse File:
                            <input type="file" name="excelImport" id="excelImport">
                            </label>
                        </div>
                        <!-- <div class="col-sm-2">
                            <label style="width: 100%">Effect On
                            <select id="valueType" class="form-control" name="valueType">
                                <option value="op">Opening Grade</option>
                                <option value="ad">Additional Grade</option>
                                <option value="gv">Grade Value</option>
                            </select>
                            </label>
                        </div> -->
                        <div class="col-sm-2">
                            <label>Leave Year</label>
                            <?php print $this->formElement($leaveYearSelect); ?>
                        </div>
                        
                        <div class="col-sm-2">
                            <div class="row">
                                <span>Based On:</span>
                                <div class="col-sm-12">
                                    <label>Employee Id</label>
                                    <input type="radio" name="basedOn" id="employeeIdBased">
                                </div>
                                <div class="col-sm-12">
                                    <label>Official Code</label>
                                    <input type="radio" name="basedOn" checked="checked" id="employeeCodeBased">
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-2">
                            <input class="btn btn-primary" type="button" name="submit" value="submit" id="submit">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="table"></div>



