<?php
$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
    ->appendFile($this->basePath('js/angular.min.js'))
    ->appendFile($this->basePath('js/search.js'))
    ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
    ->appendFile($this->basePath('js/AttendanceManagement/special-attendance/assign.js'));
?>

<script>
    document.searchValues =<?php echo json_encode($searchValues); ?>;
    document.wsGetEmployeeList = '<?php echo $this->url('special-attendance', ['action' => 'getEmployeeList']); ?>';
    document.wsGetAssignedEmployees = '<?php echo $this->url('special-attendance', ['action' => 'getAssignedEmployees']); ?>';
    document.wsAssignSpToEmployees = '<?php echo $this->url('special-attendance', ['action' => 'assignSpToEmployees']); ?>';
    document.spList =<?php echo json_encode($spList); ?>;
    document.acl =<?php echo json_encode($acl); ?>;
    document.employeeDetail =<?php echo json_encode($employeeDetail); ?>;
    document.braProv = <?php echo json_encode($braProv);?>;
</script>
<div class="page-bar">
<?= $this->navigation('Zend\Navigation\holiday-assign')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}

?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="" ng-app="hris" ng-controller="HolidayAssignController">
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-paper-plane font-green-haze"></i>
                <span class="caption-subject bold font-green-haze uppercase"> Search</span>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-sm-2">
                    <label>Company</label>
                    <select multiple class="form-control" name="company" id="companyId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Branch</label>
                    <select multiple class="form-control" name="branchId" id="branchId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Department</label>
                    <select multiple class="form-control" name="department" id="departmentId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Designation</label>
                    <select multiple class="form-control" name="designation" id="designationId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Position</label>
                    <select multiple class="form-control" name="position" id="positionId">
                    </select>
                </div>
            </div>
            <div class="row margin-top-10 margin-bottom-20">
                <div class="col-sm-2">
                    <label>Service Type</label>
                    <select multiple class="form-control" name="serviceType" id="serviceTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Service Event Type</label>
                    <select multiple class="form-control" name="serviceEventType" id="serviceEventTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Gender</label>
                    <select multiple class="form-control" name="gender" id="genderId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Employee Type</label>
                    <select multiple class="form-control" name="employeeType" id="employeeTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Employee</label>
                    <select multiple class="form-control" name="employee" id="employeeId">
                    </select>
                </div>
            </div>
            <?php if($preference['provinceWiseBranchFilter'] == 'Y') {?>
                <div class="row margin-top-10">
                    <div class="col-sm-2">
                        <label>Province</label>
                        <select class="form-control reset-field" name="province[]" id="province">
                            <option>-----</option>
                            <?php foreach($provinces as $key => $value ){?>
                                <option value='<?=$key?>'><?=$value?></option>
                            <?php  }?>
                        </select>
                    </div>
                </div>
            <?php } ?>

            <div class="row margin-top-10 margin-bottom-20">
                <div class=" col-sm-offset-8 col-sm-4 ">
                    <button id="reset" class="btn default btn-sm pull-right hris-reset-btn ">
                        Reset
                        <i class="fa fa-refresh"></i>
                    </button>
                    <button  ng-click="view()" class="btn btn-default btn-sm pull-right">
                        Search
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>

            <div class="scroller"  style="min-height:300px;height: 400px;" id="loadingDiv">
                <table id="employeeTable" class="table table-striped table-bordered table-hover no-footer custometbletwo">
                    <thead>
                        <tr>
                            <th>
                                Code
                            </th>
                            <th>
                                Employee
                            </th>
                            <th>
                                Branch
                            </th>
                            <th>
                                Department
                            </th>
                            <th>
                                Designation
                            </th>
                            <th>
                                Position
                            </th>
                            <th>
                                Service Type
                            </th>
                            <th class="bs-checkbox " style="width: 36px; " data-field="state" tabindex="0">
                                <div class="th-inner ">
                                    <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                        <input class="" type="checkbox" ng-model="all" ng-click="checkAll(all)"/>
                                        <span></span>
                                    </label>
                                </div>
                                <div class="fht-cell" style="width: 46px;"></div>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr ng-repeat="employeeShift in employeeList track by $index">
                            <td>
                                <span ng-bind="employeeShift.EMPLOYEE_CODE"></span>
                            </td>
                            <td>
                                <span ng-bind="employeeShift.FIRST_NAME"></span>
                                <span ng-bind="employeeShift.MIDDLE_NAME"></span>
                                <span ng-bind="employeeShift.LAST_NAME"></span>
                            </td>
                            <td ng-bind="employeeShift.BRANCH_NAME">
                            </td>
                            <td ng-bind="employeeShift.DEPARTMENT_NAME">

                            </td>
                            <td ng-bind="employeeShift.DESIGNATION_TITLE">
                            </td>
                            <td ng-bind="employeeShift.POSITION_NAME">
                            </td>
                            <td ng-bind="employeeShift.SERVICE_TYPE_NAME">
                            </td>
                            <td class="bs-checkbox " style="width: 36px; " data-field="state" tabindex="0">
                                <div class="th-inner ">
                                    <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                        <input class="" ng-model="employeeShift.checked" type="checkbox"
                                               ng-change="checkUnit($index, employeeShift.EMPLOYEE_ID,  employeeShift.checked)"/>
                                        <span></span>
                                    </label>
                                </div>
                                <div class="fht-cell" style="width: 46px;"></div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>   

            <div class="row margin-top-30" >
                <div class="col-sm-2">
                    <select  ng-options="sp.ID as sp.SP_EDESC for sp in spList" ng-model="sp" ng-change="spChangeFn()" class="form-control" name="sp" id="spId">
                        <option value="">Select Attendance Type</option>
                    </select>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <input type="text" id="fromDate" class="form-control" placeholder="From Date" ng-model="date" ng-change="spChangeFn()"/>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <input type="text" id="nepaliFromDate" class="form-control" placeholder="From Date Nepali"/>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <input type="text" id="toDate" class="form-control" placeholder="To Date" ng-model="todate"/>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <input type="text" id="nepaliToDate" class="form-control" placeholder="To Date Nepali"/>
                    </div>
                </div>
                <div class="col-sm-2">
                <label for="displayInOutFlag">
                    <input type="checkbox" id="displayInOutFlag" name="displayInOutFlag"/>
                Display In Out Time
                </label>
                </div>
                <div class="col-sm-2">
                    <button class="pull-right btn btn-sm btn-primary"  ng-click="assign()">
                        Assign
                        <i class="fa fa-edit"></i>
                    </button>
                </div>
            </div>


        </div>
    </div>



</div>
