<?php
$spCode = $form->get('spCode');
$spEdesc = $form->get('spEdesc');
$remarks = $form->get('remarks');
$submit = $form->get('submit');
$form->setAttribute('action', $this->url('special-attendance', ['action' => 'edit', 'id' => $id]));
?>

<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>

                <div class="row">
                    <div class="col-sm-12 col-md-6 col-lg-4">
                        <div class="form-group">
                            <?php print $this->formLabel($spCode); ?>
                            <?php print $this->formElement($spCode); ?>
                            <?php print $this->formElementErrors()->render($spCode, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-6 col-lg-4">
                        <div class="form-group">
                            <?php print $this->formLabel($spEdesc); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($spEdesc); ?>
                            <?php print $this->formElementErrors()->render($spEdesc, ['class' => 'help-block error']); ?>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-6 col-lg-4">
                        <div class="form-group">
                            <?php print $this->formLabel($remarks); ?>
                            <?php print $this->formElement($remarks); ?>
                            <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>

                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>

</div>

