<?php
$this->headScript()->appendFile($this->basePath('js/setup/level/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'level-form');

$levelCode = $form->get('levelCode');
$levelName = $form->get('levelName');
$remarks = $form->get('remarks');


// $levelId = $form->get('levelId');

$amount = $form->get('amount');


$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('level', ['action' => 'edit', 'id' => $id]));

if ($this->messages) {
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message) {
        print '<li>' . $message . '</li>';
    }
    print '</ul>';
}

$form->prepare();
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\Level')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Update
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>

                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($levelCode); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($levelCode); ?>
                            <?php print $this->formElementErrors()->render($levelCode, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group <?= empty($levelName->getMessages()) ? "" : "has-error" ?>">
                            <?php print $this->formLabel($levelName); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($levelName); ?>
                            <?php print $this->formElementErrors()->render($levelName, ['class' => 'help-block']); ?>
                            <input type="hidden" id="positionId" value="<?php echo $id; ?>"/>
                        </div>
                    </div>

                </div>
                <div class="row">

                    <div class="col-sm-4">
                        <div class="form-group <?= empty($amount->getMessages()) ? "" : "has-error" ?>">
                            <?php print $this->formLabel($amount); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($amount); ?>
                            <?php print $this->formElementErrors()->render($amount, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    
                    <div class="col-sm-4">
                        <div class="form-group <?= empty($remarks->getMessages()) ? "" : "has-error" ?>">
                            <?php print $this->formLabel($remarks); ?>
                            <?php print $this->formElement($remarks); ?>
                            <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                </div>



                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
